name: 'Run JAX Tests'
description: 'Install dependencies and run pytest with JAX'

inputs:
  python-version:
    description: 'Python version to test'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (with JAX)
      shell: bash
      run: uv sync --frozen --group test --group jax

    - name: Run tests
      shell: bash
      run: uv run --frozen pytest -s -v
