name: 'Run SciPy Tests'
description: 'Install dependencies and run pytest with SciPy'

inputs:
  python-version:
    description: 'Python version to test'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (with SciPy)
      shell: bash
      run: uv sync --frozen --group test

    - name: Run tests
      shell: bash
      run: uv run --frozen pytest -s -v
